import { Threat, Endpoint, ComplianceScore, ScanResult, AIInsight, NetworkNode, NetworkLink } from '@/types/security';

export const mockThreats: Threat[] = [
  {
    id: 'threat-001',
    title: 'Ransomware Attack Detected',
    description: 'LockBit 3.0 ransomware signature detected attempting to encrypt files on endpoint WS-FINANCE-04',
    severity: 'critical',
    status: 'active',
    source: 'External IP: 185.220.101.34',
    targetAsset: 'WS-FINANCE-04',
    timestamp: new Date(Date.now() - 120000),
    mitreTactic: 'Impact',
    mitreTechnique: 'T1486 - Data Encrypted for Impact',
    killChainPhase: 'Actions on Objectives',
    ipAddress: '185.220.101.34',
    affectedEndpoints: 1,
    confidenceScore: 98,
  },
  {
    id: 'threat-002',
    title: 'Brute Force Login Attempt',
    description: 'Multiple failed authentication attempts detected from suspicious IP targeting admin accounts',
    severity: 'high',
    status: 'investigating',
    source: 'External IP: 45.95.169.22',
    targetAsset: 'Azure AD',
    timestamp: new Date(Date.now() - 300000),
    mitreTactic: 'Credential Access',
    mitreTechnique: 'T1110 - Brute Force',
    killChainPhase: 'Weaponization',
    ipAddress: '45.95.169.22',
    affectedEndpoints: 0,
    confidenceScore: 94,
  },
  {
    id: 'threat-003',
    title: 'Suspicious Data Exfiltration',
    description: 'Unusual outbound traffic pattern detected - 2.3GB transferred to unknown external endpoint',
    severity: 'high',
    status: 'active',
    source: 'Internal: SRV-DB-01',
    targetAsset: 'Customer Database',
    timestamp: new Date(Date.now() - 600000),
    mitreTactic: 'Exfiltration',
    mitreTechnique: 'T1041 - Exfiltration Over C2 Channel',
    killChainPhase: 'Actions on Objectives',
    ipAddress: '103.45.67.89',
    affectedEndpoints: 1,
    confidenceScore: 87,
  },
  {
    id: 'threat-004',
    title: 'Privilege Escalation Detected',
    description: 'User account "jsmith" elevated to domain admin without proper authorization workflow',
    severity: 'medium',
    status: 'mitigated',
    source: 'Internal: DC-01',
    targetAsset: 'Active Directory',
    timestamp: new Date(Date.now() - 1800000),
    mitreTactic: 'Privilege Escalation',
    mitreTechnique: 'T1078 - Valid Accounts',
    killChainPhase: 'Exploitation',
    affectedEndpoints: 0,
    confidenceScore: 92,
  },
  {
    id: 'threat-005',
    title: 'Phishing Email Campaign',
    description: '47 users received sophisticated spear-phishing emails impersonating CEO',
    severity: 'medium',
    status: 'investigating',
    source: 'Email Gateway',
    targetAsset: 'Email Infrastructure',
    timestamp: new Date(Date.now() - 3600000),
    mitreTactic: 'Initial Access',
    mitreTechnique: 'T1566 - Phishing',
    killChainPhase: 'Delivery',
    affectedEndpoints: 47,
    confidenceScore: 96,
  },
  {
    id: 'threat-006',
    title: 'Lateral Movement Detected',
    description: 'Suspicious RDP connections from compromised workstation to multiple servers',
    severity: 'high',
    status: 'active',
    source: 'Internal: WS-IT-07',
    targetAsset: 'Server Infrastructure',
    timestamp: new Date(Date.now() - 900000),
    mitreTactic: 'Lateral Movement',
    mitreTechnique: 'T1021 - Remote Services',
    killChainPhase: 'Lateral Movement',
    ipAddress: '10.0.1.107',
    affectedEndpoints: 4,
    confidenceScore: 89,
  },
];

export const mockEndpoints: Endpoint[] = [
  { id: 'ep-001', name: 'SRV-WEB-01', type: 'server', status: 'online', lastSeen: new Date(), os: 'Windows Server 2022', ip: '10.0.1.10', riskScore: 23, threats: 0 },
  { id: 'ep-002', name: 'SRV-DB-01', type: 'server', status: 'online', lastSeen: new Date(), os: 'Ubuntu 22.04 LTS', ip: '10.0.1.20', riskScore: 67, threats: 1 },
  { id: 'ep-003', name: 'WS-FINANCE-04', type: 'workstation', status: 'compromised', lastSeen: new Date(), os: 'Windows 11 Pro', ip: '10.0.2.104', riskScore: 95, threats: 2 },
  { id: 'ep-004', name: 'WS-IT-07', type: 'workstation', status: 'isolated', lastSeen: new Date(Date.now() - 3600000), os: 'Windows 11 Pro', ip: '10.0.1.107', riskScore: 88, threats: 1 },
  { id: 'ep-005', name: 'DC-01', type: 'server', status: 'online', lastSeen: new Date(), os: 'Windows Server 2022', ip: '10.0.1.5', riskScore: 34, threats: 0 },
  { id: 'ep-006', name: 'FW-EDGE-01', type: 'server', status: 'online', lastSeen: new Date(), os: 'FortiOS 7.4', ip: '10.0.0.1', riskScore: 12, threats: 0 },
  { id: 'ep-007', name: 'CLOUD-K8S-PROD', type: 'cloud', status: 'online', lastSeen: new Date(), os: 'Azure AKS', ip: '20.185.45.67', riskScore: 45, threats: 0 },
  { id: 'ep-008', name: 'IOT-CAMERA-LOBBY', type: 'iot', status: 'online', lastSeen: new Date(), os: 'Linux Embedded', ip: '10.0.5.201', riskScore: 56, threats: 0 },
];

export const mockCompliance: ComplianceScore[] = [
  { framework: 'SOC 2 Type II', score: 87, status: 'partial', lastAudit: new Date(Date.now() - 86400000 * 30), gaps: 4 },
  { framework: 'ISO 27001', score: 92, status: 'compliant', lastAudit: new Date(Date.now() - 86400000 * 14), gaps: 2 },
  { framework: 'GDPR', score: 78, status: 'partial', lastAudit: new Date(Date.now() - 86400000 * 7), gaps: 7 },
  { framework: 'HIPAA', score: 94, status: 'compliant', lastAudit: new Date(Date.now() - 86400000 * 21), gaps: 1 },
];

export const mockScans: ScanResult[] = [
  { id: 'scan-001', type: 'network', status: 'scanning', startTime: new Date(Date.now() - 120000), findings: 12, criticalFindings: 2, progress: 67 },
  { id: 'scan-002', type: 'vulnerability', status: 'completed', startTime: new Date(Date.now() - 3600000), endTime: new Date(Date.now() - 1800000), findings: 34, criticalFindings: 5, progress: 100 },
  { id: 'scan-003', type: 'identity', status: 'completed', startTime: new Date(Date.now() - 7200000), endTime: new Date(Date.now() - 5400000), findings: 8, criticalFindings: 1, progress: 100 },
  { id: 'scan-004', type: 'cloud', status: 'idle', startTime: new Date(Date.now() - 86400000), endTime: new Date(Date.now() - 82800000), findings: 23, criticalFindings: 3, progress: 100 },
  { id: 'scan-005', type: 'misconfiguration', status: 'scanning', startTime: new Date(Date.now() - 60000), findings: 5, criticalFindings: 0, progress: 34 },
];

export const mockInsights: AIInsight[] = [
  {
    id: 'insight-001',
    type: 'prediction',
    title: 'Elevated Attack Probability',
    content: 'Based on current threat patterns and external intelligence, there is a 78% probability of targeted ransomware attack within the next 48 hours. Recommend immediate backup verification and endpoint hardening.',
    confidence: 78,
    timestamp: new Date(Date.now() - 300000),
    relatedThreats: ['threat-001'],
  },
  {
    id: 'insight-002',
    type: 'recommendation',
    title: 'Critical Patch Required',
    content: 'CVE-2024-3400 affecting Palo Alto PAN-OS detected in your environment. This zero-day is actively exploited. Immediate patching recommended for FW-EDGE-01.',
    confidence: 95,
    timestamp: new Date(Date.now() - 600000),
  },
  {
    id: 'insight-003',
    type: 'analysis',
    title: 'Attack Chain Correlation',
    content: 'AI analysis indicates threats threat-002, threat-004, and threat-006 may be part of coordinated APT campaign. Tactics align with APT29 (Cozy Bear) behavior patterns.',
    confidence: 82,
    timestamp: new Date(Date.now() - 900000),
    relatedThreats: ['threat-002', 'threat-004', 'threat-006'],
  },
];

export const mockNetworkNodes: NetworkNode[] = [
  { id: 'firewall', label: 'Edge Firewall', type: 'firewall', status: 'healthy', x: 400, y: 50 },
  { id: 'router', label: 'Core Router', type: 'router', status: 'healthy', x: 400, y: 150 },
  { id: 'srv-web', label: 'Web Server', type: 'server', status: 'healthy', x: 200, y: 250 },
  { id: 'srv-db', label: 'Database', type: 'server', status: 'warning', x: 400, y: 250 },
  { id: 'srv-app', label: 'App Server', type: 'server', status: 'healthy', x: 600, y: 250 },
  { id: 'cloud', label: 'Azure Cloud', type: 'cloud', status: 'healthy', x: 150, y: 350 },
  { id: 'ws-finance', label: 'WS-FINANCE-04', type: 'endpoint', status: 'critical', x: 350, y: 350 },
  { id: 'ws-it', label: 'WS-IT-07', type: 'endpoint', status: 'warning', x: 550, y: 350 },
  { id: 'threat-actor', label: 'Threat Actor', type: 'threat', status: 'critical', x: 700, y: 450 },
];

export const mockNetworkLinks: NetworkLink[] = [
  { source: 'firewall', target: 'router', type: 'normal', bandwidth: 95 },
  { source: 'router', target: 'srv-web', type: 'normal', bandwidth: 45 },
  { source: 'router', target: 'srv-db', type: 'suspicious', bandwidth: 78 },
  { source: 'router', target: 'srv-app', type: 'normal', bandwidth: 34 },
  { source: 'srv-web', target: 'cloud', type: 'normal', bandwidth: 23 },
  { source: 'srv-db', target: 'ws-finance', type: 'malicious', bandwidth: 89 },
  { source: 'srv-app', target: 'ws-it', type: 'suspicious', bandwidth: 67 },
  { source: 'ws-it', target: 'threat-actor', type: 'malicious', bandwidth: 100 },
];

export const generateLiveMetrics = () => ({
  threatsBlocked: Math.floor(Math.random() * 50) + 150,
  activeScans: Math.floor(Math.random() * 3) + 1,
  endpointsMonitored: 847,
  riskScore: Math.floor(Math.random() * 15) + 65,
  networkTraffic: Math.floor(Math.random() * 500) + 2000,
  anomaliesDetected: Math.floor(Math.random() * 10) + 5,
});
